### ISSUE TITLE
mod_mods_gui suggestions and questions

### ISSUE THREAD

**Issue by CH4MPi** [spoter/spoter-mods#35]
Hi spoter,

Suggestion #1:
i have a little suggestion for your mods gui. How about a functions in the settings dialog near the "enable" button to reset all settings of a mod to default? The settings are already there in config.data you know. This would allow a user to set all back to default. 

Suggestion #2:
how about an "About" Button for each mod that is registered in the mods gui? It can be used for autor informations, version number, changelog or something else like that.

What do you think?

Question #1:
Is it possible to define an text input field in the template? Would be great for user input.

Question #2:
Is it possible to control the sort order (without changing the name) of the registered mods in mods gui? 

Question #3:
Is is possible to set a checkbox in relation to another setting? e.g. Checkbox1 is unchecked and that will disable CheckBox2 ?

regards

**Comment by spoter** [comment]
1. Interested. Im try.
2. Interested, im try create that

1. Yes, that possible. Check source fakeCheat
2. No, Flash limit, used net sort orders dictonary. 
3. No. Sorry.

**Comment by Paxifixi** [comment]
I have also 2 more language files for the mods_gui. If you're interested in it please create the folder structure for it in the repo as you want it, because only the zip archive is visible.

to Question #2: when the sort order is not changeable as you say, is it possible to make something like a quickselect? (like a dropdownmenu, or like a search field to show only mods that are matching the search pattern? The reason behind this is the number of mods i use and the time it takes to find the one i want to edit the settings. for 1-3 mods, this is not needed, but for 10 or more its still an option, right? :)

to Question 5: really not? I thought its exactly the same when you toogle the main switch for the mod, which disables all settings for it. Too bad that it doesn't work :(

**Comment by CH4MPi** [comment]
> Suggestion #2:
how about an "About" Button for each mod that is registered in the mods gui? It can be used for autor informations, version number, changelog or something else like that.

Any news about this? need this function :)

**Comment by spoter** [comment]
https://github.com/spoter/spoter-mods/blob/master/mod_fakeCheats/source/mod_fakeCheats.py
Try use LABEL
